phoenix-rtos/phoenix-rtos-filesystems

- dummyfs/dummyfs.c
This way we know for sure the dummyfs is mounted after it exits.
> dummyfs: add option to daemonize after initialization

- ext2/block.c
- ext2/pc-ata.c
The lack of buys bit polling after issuing a command caused the phoenix system to crash on virtualbox.
> pc-ata fix

- Makefile.armv7-imxrt
The spi's stm32-multi.h dependecy prevents to build meterfs on armv7-imxrt target.
> meterfs: temporary fix for armv7-imxrt target build

- meterfs-srv/meterfs.c
Accordingly to phoenix-rtos/libphoenix#70 (comment)
> Unify use of the rid parameter of msgRecv, msgRespond functions

- dummyfs/dev.c
- dummyfs/dir.c
`dummyfs.c:584`
calling function `dummyfs_create`, 5th argument is `NULL`
```
dummyfs_create(&root, "syspage", &sysoid, S_IFDIR | 0666, NULL);
```
`dummyfs.c:405`
calling function `dev_find`, 1st argument is `NULL`
```
o = dev_find(dev, 1);
```
`dev.c:57`
dereferencing argument `oid` that is `NULL`
```
memcpy(&find.dev, oid, sizeof(oid_t));
```
Now there is first assignment, then a pointer check.
> dummyfs: fixed null pointer dereference

- meterfs/meterfs.c
There was inappropriate handling of return value from `meterfs_resizeFile()` function in `meterfs_devctl()` switch case.
> meterfs: fixed resize bug

- meterfs/meterfs.c
Issue #30 is fixed. Change in meterfs.h prevent of existance of same issue in [#4](https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/4).
> meterfs: fixed compilation warning of strncpy

- meterfs/meterfs.c
There was unneeded call of node_put() function which was causing deletion of node after it has been found in tree structure.
> meterfs: fixed lookup bug

- meterfs/meterfs.c
- meterfs/node.c
- meterfs/node.h
Building of tree moved from lookup() to init() and allocateFile(). There is no removing files feature in meterfs so, node_put() function has been removed as well as "refs" field from node_t type.
> meterfs: reworked rbtree building

- dummyfs/dummyfs.c
- ext2/ext2.c
- ext2/libext2.c
- jffs2/jffs2.c
Needed for `realpath()` to work sensibly.
JIRA: DTR-75
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/112
> Fix/enhance getAttr/setAttr and add symlink creation support to ext2

- ext2/obj.c
Added fs->root NULL initialization.
Mounting ext2 filesystem caused page fault exception (the problem appeared while developing new plo ia32-generic implementation).
[JIRA issue](https://jira.phoenix-rtos.com/browse/RTOS-66)
> ext2: fix fs->root filesystem object initialization

- dummyfs/dir.c
Fixes invalid some invalid errnos in dummyfs.
JIRA: DTR-75
Needed for https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/29 to pass if `/etc` lies on `dummyfs`
> dummyfs: fix dir nonexistent errno (EINVAL -> ENOTDIR)

- jffs2/phoenix-rtos/mtd.c
- jffs2/phoenix-rtos/mtd.h
This (and connected PRs) are needed to:
- support various NAND flash types dynamically (runtime detection)
- actually manage badblocks correctly
JIRA: DTR-88
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/121
> jffs2: NAND flash support enhancements

- dummyfs/dir.c
- dummyfs/dummyfs.c
- dummyfs/dummyfs.h
- dummyfs/file.c
- dummyfs/object.c
- dummyfs: fix memory leaks
- deleted dirents for dummyfs root dir were never freed
- fixed memory leaks in error paths
- fixed ERRNO value
- dummyfs: fix realloc() usage
Also: remove unneeded chunk properly.
Fixes phoenix-rtos/phoenix-rtos-project#169
> dummyfs: memory-related fixes

- _targets/Makefile.armv7a7-imx6ull
Enabled building libmeterfs for armv7a7-imx6ull target.
[JIRA: DTR-97](https://jira.phoenix-rtos.com/browse/DTR-97)
> _targets: enable libmeterfs as default component for armv7a7-imx6ull

- meterfs/meterfs.c
- meterfs/meterfs.h
[JIRA: DTR-182](https://jira.phoenix-rtos.com/browse/DTR-182)
[JIRA: DTR-184](https://jira.phoenix-rtos.com/browse/DTR-184)
> meterfs: remove partitionErase() usage + mark it as deprecated

- dummyfs/dummyfs.c
- ext2/ext2.c
- jffs2/jffs2.c
Added support for retrieving stat.st_blocks and stat.st_blksize info.
[JIRA: DTR-205](https://jira.phoenix-rtos.com/browse/DTR-205)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/283
https://github.com/phoenix-rtos/libphoenix/pull/156
> Add 'atBlocks' and 'atIOBlock' attributes support

- ext2/ext2.c
JIRA: PD-236
ext2 currently returns `EACCES` when called on directory that is not empty. `ENOTEMPTY` may be more appropriate solution.
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/288
> ext2: unlink not empty dir correct errno

- dummyfs/dummyfs.c
Fixed double mutexUnlock() call.
[JIRA: DTR-289](https://jira.phoenix-rtos.com/browse/DTR-289)
> dummyfs: fix double mutexUnlock() in dummyfs_link()

- jffs2/phoenix-rtos/mtd.c
- jffs2/phoenix-rtos/mtd.h
Struct `flashdrv_dma_t` got renamed to `flashdrv_dmaBuff_t`.
[JIRA: DTR-169](https://jira.phoenix-rtos.com/browse/DTR-169)
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/194
> jffs2: adapt to imx6ull-flash driver interface change

- dummyfs/dummyfs.c
- ext2/ext2.c
- jffs2/libjffs2.c
This fixes `du` tool on `jffs2` filesystem. Actually, the resulting file sizes were a cummulation of 2 errors, fixed in separate commits:
* all-fs: fix getting/setting unknown attrs resulting in EOK
* jffs2: fix missing atBlocks, atIOBlock getattr
I want `du` to work.
> Fix `du` on `jffs2`

- ext2/ext2.c
- ext2: handle setting atime/mtime attributes
- fixes touch on existing file (currently not working on ia32-generic)
- JIRA: PD-304
> ext2: handle setting atime/mtime attributes

- ext2/dir.c
> ext2: Fix _ext2_dir_read() skipping last entries in a directory

- meterfs/files.h
- meterfs/meterfs.c
- meterfs/meterfs.h
JIRA: RTOS-361
Adds devctl returning info about filesystem to meterfs.
This change helps write more general meterfs tests.
> meterfs: Add fsInfo devctl

- _targets/Makefile.armv7a7-imx6ull
- meterfs/libstorage/Makefile
- meterfs/libstorage/meterfs_storage.c
- meterfs/libstorage/meterfs_storage.h
- meterfs/meterfs.c
- meterfs/meterfs.h
JIRA: RTOS-346
Modifies meterfs_ctx_t so that read, write, eraseSector, powerCtrl functions take context.
Adds context to meterfs_ctx_t.
Adds meterfs_storage library that adds meterfs_mount and meterfs_unmount needed for libstorage.
Adds wrappers around mtd functions and fsOp functions.
We are migrating imx6ull-flashnor driver to use libstorage.
https://github.com/phoenix-rtos/phoenix-rtos-corelibs/pull/34
(BREAKING CHANGE) TODO All drivers using meterfs have to be rewritten to accomodate the new API.
> Add functions needed for libstorage support to meterfs

- jffs2/libjffs2.c
- i_count hold number of memory references
- set i_count to 0 in create()
- functions increment & decrement i_count to protect access
- i_count should be 0 when functions exit
- link() shouldn't increment i_count
JIRA: DTR-401
> jffs2: fixed for last commit

- jffs2/Makefile
LIBS is not used in static-lib and this value can corrupt next binary.mk
This needs to be merged before https://github.com/phoenix-rtos/phoenix-rtos-build/pull/144
> remove LIBS sets before calling static-lib.mk

- _targets/Makefile.armv7m7-imxrt106x
Adds `libdummyfs` for optional support to be built into `imxrt-multi`.
The classic dummyfs server is also built independently depending on that how memory is divided and how booting is done, whether from xip or ram, it is left to the project implementer to choose whether to use either a clasic dummyfs server or imxrt-multi with dummyfs embedded.
JIRA: NIL-432
> _targets: add libdummyfs for imxrt targets

- _targets/Makefile.armv7m3-stm32l152xd
- _targets/Makefile.armv7m4-stm32l4x6
- _targets/Makefile.armv7m7-imxrt106x
Each target now have access to global `__TARGET_*` and `__CPU_*` defined by phoenix-rtos-build system. Local TARGET defines becomes redundant, especially if they haven't been used.
JIRA: RTOS-519
> makes: remove TARGET define

- jffs2/libjffs2.c
- jffs2/phoenix-rtos/fs.h
- jffs2/phoenix-rtos/phoenix-rtos.c
Fixed setting newly created file attributes (they were previously hardcoded).
Fixed setting file atime, mtime and ctime by addding `get_seconds()` implementation (previously returned 0).
Fixed device file type (character, block or fifo) to `otDev` conversion.
[JIRA: DTR-368](https://jira.phoenix-rtos.com/browse/DTR-368)
> jffs2: fix file attributes

- dummyfs/dev.c
- dummyfs/dev.h
- dummyfs/dummyfs.c
- dummyfs/dummyfs_internal.h
- dummyfs/srv.c
JIRA: RTOS-255
Dummyfs is now able to mount other filesystems.
In lookup added checking for mountpoints, also now lookup sets correct oid->dev.
In dev_find added changes that allow to correctly assign object with device.
This change was required for dummyfs to be able to mount other filesystems.
> dummyfs: add mounting capabilities to dummyfs

- jffs2/phoenix-rtos/fs.h
Remnant of switching globally to LSB d_types.
Fixes: phoenix-rtos/phoenix-rtos-project#889
> jffs2: fix readdir returned direntry d_type

- _targets/Makefile.armv7a9-zynq7000
- ext2/block.c
- ext2/ext2.c
- ext2/ext2.h
- ext2/libext2.c
- ext2/libext2.h
- ext2/sb.c
Modified `libext2` to make it compatible with `libstorage`. This will make the filesystem driver compatible with storage device drivers based on `libstorage`.
Message handling performed by the `libext2_handler` was split into separate functions that are compatible with the `libstorage` API for file systems.
Compatibility with `pc-ata` storage driver (that uses the current API for handling ext2 filesystems) was not affected.
Additionally, length checks on file names were added (previously name lengths could cause integer overflow).
ext2 filesystem would be useful for data exchange using [SD cards](https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/433) as ext2 can be easily mounted on many host PC operating systems.
> ext2: add compatibility with libstorage

- ext2/ext2.c
DONE: RTOS-669
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/910
> ext2: Fix ext2_obj_get reval check in ext2_getattr

- dummyfs/dummyfs.c
- dummyfs/memory.c
- jffs2/phoenix-rtos.h
- jffs2/phoenix-rtos/mtd_em.c
JIRA: RTOS-665
Adjust mmap to POSIX standard.
https://github.com/phoenix-rtos/libphoenix/pull/306
> Adjust mmap calls to new interface

- ext2/dir.c
- ext2/dir.h
- ext2/ext2.c
- ext2/ext2.h
- ext2/libext2.c
- ext2/obj.c
- ext2/obj.h
Added the ability to mount a different filesystem within an ext2 filesystem.
Now another filesystem can be mounted using a directory within ext2 as the mountpoint. 
Additionally, the ext2 filesystem driver had a path length limit of 255 characters. This limitation has been removed and now paths of any length can be looked up within ext2. Single file names are still limited to 255 characters, as this is a file system limitation.
This also fixes issue https://github.com/phoenix-rtos/phoenix-rtos-project/issues/749 (on ext2 only).
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/114
> ext2: Add ability to mount devices and filesystems

- dummyfs/dummyfs.c
- dummyfs/dummyfs.h
- ext2/dir.c
- ext2/dir.h
- ext2/ext2.c
- ext2/ext2.h
- ext2/file.c
- ext2/file.h
- ext2/libext2.c
- ext2/libext2.h
- fat/fatchain.c
- fat/fatdev.c
- fat/fatdev.h
- fat/fatio.c
- fat/fatio.h
- fat/libfat.c
- jffs2/libjffs2.c
- meterfs/libstorage/meterfs_storage.c
JIRA: RTOS-125
Adapt to the removal of `offs_t` type
> use off_t instead of offs_t

- ext2/block.c
- ext2/ext2.h
- ext2/file.c
Fix error in block allocation function that resulted in freezes if the next available block was the last one in group.
The error was in `ext2_block_create` because of the comparison `offset + i < fs->sb->groupBlocks` instead of `offset + i <= fs->sb->groupBlocks`. Variable `offset` has values [0 .. `fs->sb->groupBlocks`] inclusive, with 0 indicating invalid value. Due to this faulty comparison, the function sometimes returned `EOK` while setting number of blocks allocated to 0. As a result, the loop in `ext2_block_sync` which uses this function would loop infinitely.
To fix this, the comparison was corrected and an explicit check was added to ensure that `*res` is never set to 0, instead returning with `-ENOSPC`.
Additionally, code style was improved in several functions to make it more …
> ext2: fix block allocation error

- jffs2/phoenix-rtos.h
- jffs2/phoenix-rtos/phoenix-rtos.c
This is needed to compile with `-fno-common` flag. See https://github.com/phoenix-rtos/phoenix-rtos-build/pull/181
> jffs2/phoenix-rtos: add `extern` keyword to init_user_ns

- meterfs/crypt.c
- meterfs/crypt.h
- meterfs/files.h
- meterfs/meterfs.c
- meterfs/meterfs.h
JIRA: NIL-523
Add AES option to meterfs. This change does not compromise existing API nor existing meterfs partitions data.
> meterfs: Add file payload encryption option

- meterfs/files.h
- meterfs/meterfs.c
- meterfs/meterfs.h
Erases sector for new record after writing current record. This guarantees that next write will be done quickly because sector is already erased.
JIRA: NIL-585
> meterfs: introduce early erase filesystem option

- meterfs/libstorage/meterfs_storage.c
> libstorage: Fix meterfs usage, add missing set of keyInit field

- _targets/Makefile.armv7m7-imxrt106x
- rofs/Makefile
- rofs/rofs.c
- rofs/rofs.h
- rofs/srv.c
Filesystem on imxrt-NIL target.
To create image use tool in this PR:
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/54
JIRA: NIL-489
This file system is dedicated to storing files in read-only form. The file system image must be placed in the physical address space, as is the case with i.MX RT, where NOR/flash memory is mapped to AHB spaces. The whole thing has been designed to take up as little resources as possible. Requires additional tool to create the image.
*Why wasn't TAR used?*
Because it would require RAM to be allocated across nodes, making it unsuitable for targets with limited RAM resources.
*What is the actual RAM usage?*
*Example (used /etc dir from ia32 target)*
*Ptable support could easily be added in the future.*
*Structure*
--------------
Server supports …
> rofs: introduce readonly file system

- jffs2/libjffs2.c
Device unlinking should also be reflected in the `dev_common->dev_ino`, `dev_common->dev_oid` rbtrees. Otherwise, they will forever map the device oid to the inode of the unlinked device, making future create calls for the same oid ineffective
JIRA: RTOS-915
> jffs2: remove unlinked device from the dev_common trees

- ext2/ext2.c
If `ext2_obj_get(fs, res->id)` returned NULL, then `ext2_unlink()` would be called with `dir->lock` already obtained. A call to `ext2_unlink()` also tries to obtain this lock, which resulted in a deadlock.
JIRA: RTOS-933
> ext2: fix deadlock when ext2_obj_get() fails

- rofs/rofs.c
JIRA: RTOS-927
If "\0" was passed unitialzed `res` would be returned
> rofs: handle empty string in lookup

- rofs/rofs.c
JIRA: RTOS-961
Previously dirfind was broken if there were two folder with common prefix in the name ex `lib` and `libexec`
sparc
> rofs: allow dir names to have common prefix

- _targets/Makefile.armv7m7-imxrt106x
- rofs/Makefile
- rofs/rofs.c
- rofs/rofs.h
- rofs/srv.c
Currently rofs assumes the partition to be accessible from AHB. This change allows for defining custom dev read handlers to get rid of this assumption and using some intermediary IO provider (e.g. flashsrv)
> rofs: generalize dev read to allow for indirect memory access

- meterfs/meterfs.c
Common usage of meterfs involves using static fd table in zeroed bss. This causes that programmer error (eg. invalid initialisation) can lead to weird and hard to identify errors, that someone writes to firstly created file, instead of proper one.
Starting id from 1 can help to avoid that kind of issues.
> meterfs: Start file id's from 1
