- meterfs/flash.c
Depends on https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/58
> meterfs: Adjust SPI messages to changes in stm32lx-multi

- meterfs-srv/flash.c
Depends on https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/58
> meterfs-srv: Adjust SPI messages to changes in stm32lx-multi

- meterfs/files.h
- meterfs/meterfs.c
- meterfs/meterfs.h
- meterfs/node.c
- meterfs/node.h
I made feature branch for these changes called meterfs-PC, maybe that wasn't necessary.
> Changes necessary to build meterfs for host-pc

- dummyfs/dummyfs.c
> dummyfs: fix FIFO files handling

- dummyfs/dummyfs.c
> dummyfs: Fix coding style

- dummyfs/srv.c
> dummyfs: remove obsolete code paths

- jffs2/phoenix-rtos/mtd.c
Changed page programming so that we no longer need to read the metadata.
[JIRA: DTR-109](https://jira.phoenix-rtos.com/browse/DTR-109)
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/126
> jffs2: remove reading metadata in mtd_write()

- dummyfs/dummyfs.c
JIRA: PD-224
Changed `OBJ_MODE_MEM` macro to consist correct file type and permissions preserving its "magic number" characteristics.
Two bytes used for file properties are set via flags, and higher two bytes are _magic number_ to distinguish whole macro used.
- https://github.com/phoenix-rtos/phoenix-rtos-project/issues/285
> dummyfs: OBJECT_MODE_MEM consists of correct file type/permissions

- dummyfs/dummyfs.c
- ext2/ext2.c
- jffs2/jffs2.c
`atMode` message can change only file permissions.
The change allows for simplified `posix_chmod()` implementation in kernel.
Fixes `chmod()` usage for changing file permissions.
[JIRA: RTOS-148](https://jira.phoenix-rtos.com/browse/RTOS-148)
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/288
https://github.com/phoenix-rtos/libphoenix/pull/160
> Restrict setting file mode (atMode attribute) to permission bits only

- meterfs/files.h
- meterfs/meterfs.c
- meterfs/meterfs.h
- meterfs/node.c
- verify after write,
- checksum (BCC) for headers and records,
- read/write retry,
- partial erase (sector cleanup after bad write)
DTR-179
Solves https://github.com/phoenix-rtos/phoenix-rtos-filesystems/issues/20
> meterfs: Data integrity enhancements:

- dummyfs/dummyfs.c
- dummyfs/dummyfs.h
- dummyfs/srv.c
- ext2/ext2.c
- ext2/ext2.h
- ext2/libext2.c
- jffs2/jffs2.c
Added `mtStat` message handling to filesystems.
[JIRA: DTR-100](https://jira.phoenix-rtos.com/browse/DTR-100)
> dummyfs/ext2/jffs2: add mtStat message handling

- meterfs/meterfs.c
JIRA: RTOS-178
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/375
> meterfs: readRecord rewrite - fix CRC error on read with offset

- jffs2/phoenix-rtos/mtd.c
- jffs2/phoenix-rtos/mtd.h
This reverts commit ef79aac149f3fe5633874491d462edba64da9b86.
JIRA: DTR-303
> Revert "jffs2: adapt to imx6ull-flash driver interface change"

- jffs2/libjffs2.c
- jffs2/phoenix-rtos/mtd.c
> jffs2: add NAND flash memory initialization

- jffs2/phoenix-rtos/locks.c
- jffs2/phoenix-rtos/locks.h
Previous implementation starved threads due to priority inversion. Proper implementation (with no starvation and enabled priority inheritance) to be added in kernel.
[JIRA: DTR-318](https://jira.phoenix-rtos.com/browse/DTR-318)
> jffs2: implement RW semaphore as mutex to fix priority inversion issues

- ext2/file.c
Previous implementation worked only for truncate(0) and for files smaller than blocksz.
Partially fixes phoenix-rtos/phoenix-rtos-project#498
(not really, just wanted to link the issue)
> ext2: fix file truncation

- dummyfs/file.c
Ensures extended area after truncate is always zero filled.
[JIRA: RTOS-358](https://jira.phoenix-rtos.com/projects/RTOS/issues/RTOS-358?filter=allissues)
Fixes [https://github.com/phoenix-rtos/phoenix-rtos-project/issues/599](https://github.com/phoenix-rtos/phoenix-rtos-project/issues/599)
> dummyfs: ensure extended area is always zero-filled after truncate/ftruncate

- dummyfs/dummyfs.c
- ext2/ext2.c
> ext2, dummyfs: Fix truncate setting wrong errno for directories

- jffs2/libjffs2.c
Set i_count to 1 in create(). Decrement i_count by 1 in unlink(). Also added mising iput(idir) on errors.
JIRA: DTR-401
> jffs2: fixed unlink() for hard links

- _targets/Makefile.sparcv8leon3-gr716
add sparcv8leon3-gr716 target
JIRA: RTOS-251
> _targets: add sparcv8leon3-gr716 target

- _targets/Makefile.sparcv8leon3-gr716
> _targets/sparcv8leon3: add libmeterfs to makefile

- jffs2/libjffs2.c
> libjffs2: Fix handling ioctl() on regular file

- jffs2/summary.h
removes annoying compilation warnings
JIRA: CI-334
> jffs2: fix sum node union alignment

- meterfs/libstorage/meterfs_storage.c
> meterfs: Fix warning

- jffs2/phoenix-rtos/fs.h
> jffs2: use d_type defines from libphoenix

- dummyfs/srv.c
> Adapt to msgRecv, msgRespond API change

- dummyfs/dir.c
- ext2/dir.c
> Use standard dirent types instead of custom ones

- dummyfs/dummyfs.c
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/862
> dummyfs fixes

- ext2/obj.c
I added a flag to `_ext2_obj_destroy` that can be used to ignore I/O errors when destroying the object.
Currently, whenever an ext2 filesystem is unmounted the code attempts to destroy every object in memory and sync its state with structures on disk. However, if an I/O error occurs the `_ext2_obj_destroy` function exits with an error code and does not free memory allocated for the object. 
Because the filesystem unmount operation does not stop and continues freeing other filesystem structures, this leads to a resource leak whenever an I/O error occurs.
Exiting with an error code when destroying an object fails is a reasonable behavior during normal operation, however during filesystem unmounting it's more reasonable to ignore errors and continue freeing memory, as there is nothing we can …
> ext2: Ignore I/O errors when unmounting filesystem

- _targets/Makefile.sparcv8leon3-gr712rc
> _targets: add sparcv8leon3-gr712rc

- _targets/Makefile.sparcv8leon3-gr712rc
- jffs2/phoenix-rtos/crc32.c
> gr712rc: add libjffs2

- meterfs/meterfs.h
JIRA: DEND-239
Build error in DEND project on PC
> meterfs: Add missing include

- _targets/Makefile.riscv64-noelv
> _targets: add riscv64-noelv

- meterfs/meterfs.c
> meterfs: Fix error reporting from read

- _targets/Makefile.armv8r52-mps3an536
> _targets: add armv8r52-mps3an536

- _targets/Makefile.armv8m33-mcxn94x
JIRA: RTOS-881
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1120
https://github.com/phoenix-rtos/plo/pull/337
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/569
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/55
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/508
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/195
https://github.com/phoenix-rtos/libphoenix/pull/371
> Add MCX N94x target

- jffs2/libjffs2.c
- jffs2/phoenix-rtos.h
- jffs2/phoenix-rtos/kernel.h
- jffs2/super.c
> jffs2: fix warns on 64-bit targets

- _targets/Makefile.sparcv8leon-generic
- _targets/Makefile.sparcv8leon-gr712rc
- _targets/Makefile.sparcv8leon-gr716
JIRA: RTOS-883
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/229
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/520
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/141
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/617
https://github.com/phoenix-rtos/libphoenix/pull/390
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/217
https://github.com/phoenix-rtos/plo/pull/366
> _targets: rename sparcv8leon3 to sparcv8leon

- ext2/ext2.c
- ext2/file.c
> ext2: fix ctime, atime updating

- _targets/Makefile.sparcv8leon-gr740
JIRA: RTOS-883
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/389
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/632
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1260
- https://github.com/phoenix-rtos/libphoenix/pull/401
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/230
- https://github.com/phoenix-rtos/plo/pull/375
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/532
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/222
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
> _targets: add sparcv8leon-gr740

- _targets/Makefile.riscv64-noelv
> _targets/riscv64-noelv: build jffs2

- ext2/ext2.h
- ext2/file.c
This is a requirement in ext2 standard.
JIRA: RTOS-1019
> ext2: store symlinks shorter that 60 bytes in inode

- _targets/Makefile.aarch64a53-zynqmp
> _targets: add aarch64a53-zynqmp target

- _targets/Makefile.armv7r5f-zynqmp
> _targets: add armv7r5f-zynqmp target

- _targets/Makefile.riscv64-gr765
- _targets/Makefile.riscv64-grfpga
> rename noelv to grfpga, add riscv64-gr765 target

- _targets/Makefile.armv7r5f-tda4vm
> _targets: add armv7r5f-tda4vm

- rofs/rofs.c
> rofs: fix mem leak on rofs header read failure if imageAddr != 0
